/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmcrossdetector_free: (a: number, b: number) => void;
export const __wbg_wasmglitchfilter_free: (a: number, b: number) => void;
export const __wbg_wasmhysteresiscrossdetector_free: (a: number, b: number) => void;
export const __wbg_wasmpulsewidthdetector_free: (a: number, b: number) => void;
export const __wbg_wasmruntdetector_free: (a: number, b: number) => void;
export const __wbg_wasmwindowdetector_free: (a: number, b: number) => void;
export const wasmcrossdetector_new: () => number;
export const wasmcrossdetector_reset: (a: number) => void;
export const wasmcrossdetector_update: (a: number, b: number, c: number) => [number, number];
export const wasmglitchfilter_new: (a: number, b: number) => number;
export const wasmglitchfilter_reset: (a: number) => void;
export const wasmglitchfilter_update: (a: number, b: number, c: number) => [number, number];
export const wasmhysteresiscrossdetector_new: (a: number) => number;
export const wasmhysteresiscrossdetector_reset: (a: number) => void;
export const wasmhysteresiscrossdetector_update: (a: number, b: number, c: number) => [number, number];
export const wasmpulsewidthdetector_new: (a: number, b: number, c: number) => number;
export const wasmpulsewidthdetector_reset: (a: number) => void;
export const wasmpulsewidthdetector_update: (a: number, b: number, c: number) => [number, number];
export const wasmruntdetector_new: (a: number, b: number) => number;
export const wasmruntdetector_reset: (a: number) => void;
export const wasmruntdetector_update: (a: number, b: number) => [number, number];
export const wasmwindowdetector_new: (a: number, b: number) => number;
export const wasmwindowdetector_reset: (a: number) => void;
export const wasmwindowdetector_update: (a: number, b: number) => [number, number];
export const compute_bollinger: (a: number, b: number, c: number, d: number) => [number, number];
export const compute_ema: (a: number, b: number, c: number, d: number) => [number, number];
export const compute_indicator: (a: number, b: number, c: number, d: number) => [number, number];
export const compute_macd: (a: number, b: number, c: number, d: number) => [number, number];
export const compute_rsi: (a: number, b: number, c: number, d: number) => [number, number];
export const compute_sma: (a: number, b: number, c: number, d: number) => [number, number];
export const detect_cross: (a: number, b: number, c: number, d: number) => [number, number];
export const evaluate_rules: (a: number, b: number, c: number, d: number) => [number, number];
export const evaluate_rules_from_yaml: (a: number, b: number, c: number, d: number) => [number, number];
export const init: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_start: () => void;
